theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "cpu"
interval = 5

# [[block]]
# block = "load"
# interval = 1
# format = "{1m}"

[[block]]
block = "networkmanager"
on_click = "alacritty -e nmtui"
interface_name_exclude = ["br\\-[0-9a-f]{12}", "docker\\d+"]
interface_name_include = []
ap_format = "{strength}% {ssid}"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 1
format = "%a %d/%m %H:%M:%S"

[[block]]
block = "battery"
interval = 10
format = "{percentage}%"
device = "BAT1" 

# [[block]]
# block = "temperature"
# collapsed = false
# interval = 10
# format = "{average}"
# chip = "*-isa-*"