theme = "slick"
icons = "awesome"

[[block]]
block = "disk_space"
on_click = "dolphin"

[[block]]
block = "cpu"
on_click = "alacritty -e htop"
format = "{barchart} {utilization} {frequency}"
interval = 1

# [[block]]
# block = "load"
# interval = 1
# format = "{1m}"

[[block]]
block = "networkmanager"
on_click = "nm-connection-editor"
interface_name_exclude = ["br\\-[0-9a-f]{12}", "docker\\d+", "virbr\\d+"]
interface_name_include = []
ap_format = "{strength} {ssid}"

[[block]]
block = "music"
player = "spotify"
on_collapsed_click = "spotify"
buttons = ["prev", "play", "next"]

[[block]]
block = "sound"
on_click = "pavucontrol"

[[block]]
block = "time"
interval = 1
format = "%a %d/%m %H:%M:%S"

[[block]]
block = "battery"
interval = 2
format = "{percentage}"
device = "BAT1" 

# [[block]]
# block = "temperature"
# collapsed = false
# interval = 10
# format = "{average}"
# chip = "*-isa-*"
